project:
  type: website
  output-dir: docs
  

website:
  title: "Richard J May"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    background: light
    left: Copyright 2025, Richard May
    right: Built with Quarto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

