---
title: "Talks"
format: html
page-layout: full
---

### Advancing Behaviour Analysis Through Open Science: Current Practices and Future Opportunities

#### *Invited Address at the European Association for Behaviour Analysis Conference (2024)*
<br>
Science is currently undergoing an "open science revolution," characterised by a push for greater transparency, accessibility, and reproducibility. This movement, driven by concerns over the so-called "replication crisis" and the need for more robust research practices, has led to widespread changes in how research is conducted, reported, and disseminated. Against this backdrop, this presentation examines the current state of open science practices within behaviour analysis, explores some the potential benefits of wider adoption. As part of this talk, I provide an overview of key open science initiatives, such as pre-registration, open data, and replication efforts, and explore at whether such practices have been embraced within our field. I conclude by offering some practical steps that behaviour analytic researchers, practitioners, and organisations might consider in order to integrate open science practices into their work. I will argue that by embracing open science principles, behaviour analysis can increase its rigor, expand its impact, and strengthen its position in the behavioural sciences and evidence-based practice.

{{< video https://youtu.be/dQw4w9WgXcQ?feature=shared>}}


### A Critical Appraisal of Systematic Reviews and Meta-analyses Published in Behaviour Analysis Journals

#### *Experimental Analysis of Behaviour Conference, University of Chichester (2025)*
<br>
This talk examines the critical role of systematic reviews and meta-analyses in behaviour analysis, particularly their importance for evidence-based intervention selection and clinical decision-making. I outline key gold-standard methodological and reporting criteria for systematic reviews as evaluated by the AMSTAR-2 and R-AMSTAR assessment tools. Drawing on a comprehensive analysis of behaviour analysis journals, I present trends in both the prevalence and methodological quality of systematic reviews published in our field over time. The presentation concludes by identifying specific methodological and reporting deficiencies commonly observed in behaviour analytic systematic reviews and meta-analyses, offering recommendations for strengthening future research in this area.

{{< video https://youtu.be/cNEdxZURTaI?feature=shared>}}


### No Alarms and No Surprises, Please: Challenges and Opportunities in Bridging the Research-to-Practice Gap in Behaviour Analysis

#### *Invited Talk at the Experimental Analysis of Behaviour Group Conference, Bangor University (2023)*
<br>
The research-to-practice gap represents a disparity between the efficacy demonstrated in specific research contexts and the outcomes that are generated when interventions are applied in real-world scenarios. This presentation will outline some of the challenges that behaviour analysts may encounter in navigating this gap and will discuss insights garnered from recent research findings. This will include a discussion findings from SF-DDARIN projects exploring how well the Picture Exchange Communication System (PECS) is understood and implemented in special education settings in the UK. The talk will include examples work from the field of Implementation Science, coupled with developments in open science and meta-science, and provide a reflection on how these domains hold relevance for behaviour analysts in effectively translating research into practice. 

{{< video https://youtu.be/JmcA9LIIXWw?feature=shared>}}